create table if not exists public.blog_comments (
  id bigint generated by default as identity primary key,
  post_id text not null check (char_length(post_id) between 1 and 160),
  author_name text not null check (char_length(author_name) between 2 and 80),
  body text not null check (char_length(body) between 3 and 2000),
  visitor_hash text,
  status text not null default 'approved' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists blog_comments_visible_idx
  on public.blog_comments (post_id, status, created_at);

alter table public.blog_comments
  add column if not exists visitor_hash text;

create index if not exists blog_comments_rate_limit_idx
  on public.blog_comments (visitor_hash, created_at);

create table if not exists public.blog_comment_reports (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.blog_comments(id) on delete cascade,
  visitor_hash text not null,
  created_at timestamptz not null default now(),
  unique (comment_id, visitor_hash)
);

alter table public.blog_comments enable row level security;
alter table public.blog_comment_reports enable row level security;

alter table public.blog_comments
  alter column status set default 'approved';

update public.blog_comments
  set status = 'approved'
  where status = 'pending';

revoke all on table public.blog_comments from anon, authenticated;
revoke all on table public.blog_comment_reports from anon, authenticated;

grant select, insert on table public.blog_comments to service_role;
grant usage, select on sequence public.blog_comments_id_seq to service_role;
grant select, insert on table public.blog_comment_reports to service_role;
grant usage, select on sequence public.blog_comment_reports_id_seq to service_role;
